### ISSUE TITLE
The pods generated by the cronjob should be cleaned up after the job is completed

### ISSUE THREAD

**Issue by baldocarlino** [hasantayyar/restart-pods-cronjob#1]
The pod generated by the jobs finished with the status 'Completed' but is not deleted from every schedule, so the number of Pods in the k8s cluster continues to increase.
What did you expect to happen:
The pods generated by the cronjob should be cleaned up after the job is completed.

How i can do that ? thanks

**Comment by hasantayyar** [comment]
I recommend changing the history value in deployment.

https://cloud.google.com/kubernetes-engine/docs/how-to/cronjobs

**Comment by hasantayyar** [comment]
> You can configure the number of successful and failed CronJob executions that are saved, by specifying values for spec.successfulJobsHistoryLimit and spec.failedJobsHistoryLimit. By default, successfulJobsHistoryLimit is set to 3 and failedJobsHistoryLimit is set to 1.

>To disable retention of data about successful or failed jobs, set the respective value to 0. However, debugging failures may be more difficult

More details

https://cloud.google.com/kubernetes-engine/docs/how-to/cronjobs#history-limit
